# Generated by Django 4.0.3 on 2022-03-29 15:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_posts_link'),
    ]

    operations = [
        migrations.AddField(
            model_name='posts',
            name='desc',
            field=models.CharField(default='', max_length=300),
        ),
    ]
