# Generated by Django 4.0.3 on 2022-04-03 15:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0014_alter_posts_thumbnail'),
    ]

    operations = [
        migrations.AlterField(
            model_name='posts',
            name='steps',
            field=models.CharField(blank=True, max_length=10000),
        ),
    ]
