# Generated by Django 4.0.3 on 2022-04-03 16:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0015_alter_posts_steps'),
    ]

    operations = [
        migrations.RenameField(
            model_name='posts',
            old_name='steps',
            new_name='step',
        ),
        migrations.AddField(
            model_name='posts',
            name='step1',
            field=models.CharField(blank=True, max_length=10000),
        ),
        migrations.AddField(
            model_name='posts',
            name='step2',
            field=models.CharField(blank=True, max_length=10000),
        ),
        migrations.AddField(
            model_name='posts',
            name='step3',
            field=models.CharField(blank=True, max_length=10000),
        ),
        migrations.AddField(
            model_name='posts',
            name='step4',
            field=models.CharField(blank=True, max_length=10000),
        ),
        migrations.AddField(
            model_name='posts',
            name='step5',
            field=models.CharField(blank=True, max_length=10000),
        ),
        migrations.AddField(
            model_name='posts',
            name='step6',
            field=models.CharField(blank=True, max_length=10000),
        ),
        migrations.AddField(
            model_name='posts',
            name='step7',
            field=models.CharField(blank=True, max_length=10000),
        ),
        migrations.AddField(
            model_name='posts',
            name='step8',
            field=models.CharField(blank=True, max_length=10000),
        ),
        migrations.AddField(
            model_name='posts',
            name='step9',
            field=models.CharField(blank=True, max_length=10000),
        ),
        migrations.AddField(
            model_name='posts',
            name='step_title',
            field=models.CharField(blank=True, max_length=10000),
        ),
        migrations.AddField(
            model_name='posts',
            name='step_title1',
            field=models.CharField(blank=True, max_length=10000),
        ),
        migrations.AddField(
            model_name='posts',
            name='step_title2',
            field=models.CharField(blank=True, max_length=10000),
        ),
        migrations.AddField(
            model_name='posts',
            name='step_title3',
            field=models.CharField(blank=True, max_length=10000),
        ),
        migrations.AddField(
            model_name='posts',
            name='step_title4',
            field=models.CharField(blank=True, max_length=10000),
        ),
        migrations.AddField(
            model_name='posts',
            name='step_title5',
            field=models.CharField(blank=True, max_length=10000),
        ),
        migrations.AddField(
            model_name='posts',
            name='step_title6',
            field=models.CharField(blank=True, max_length=10000),
        ),
        migrations.AddField(
            model_name='posts',
            name='step_title7',
            field=models.CharField(blank=True, max_length=10000),
        ),
        migrations.AddField(
            model_name='posts',
            name='step_title8',
            field=models.CharField(blank=True, max_length=10000),
        ),
        migrations.AddField(
            model_name='posts',
            name='step_title9',
            field=models.CharField(blank=True, max_length=10000),
        ),
    ]
