# Generated by Django 4.0.3 on 2022-03-22 18:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Main', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user_profile',
            name='dob',
            field=models.DateField(blank=True, null=True),
        ),
    ]
