# Generated by Django 4.0.3 on 2022-03-22 18:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Main', '0002_user_profile_dob'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user_profile',
            name='profile_pic',
            field=models.ImageField(blank=True, upload_to='Images', verbose_name='Profile Picture'),
        ),
    ]
